lint: add cast to workaround mypy bug
The latest mypy version no longer proper recognizes the EllipsisType
sentinel with `is ...`.

src/tomcli/cli/set.py:441: error: "EllipsisType" not callable  [operator]